#########################################################################################
#
#  Note that import order here is important, so rearranging import lists
#  is *not* recommended.
#
#########################################################################################

- name: Install artifacts for development work
  hosts: 127.0.0.1
  connection: local

##### Operating system packages and configuration

- import_playbook: _core.yaml

##### Developer tools

# Visual Studio Code
- import_playbook: vscode/core.yaml

# Docker
- import_playbook: docker/core.yaml

# .NET
- import_playbook: dotnet/core.yaml

# git
- import_playbook: git/core.yaml

# golang
- import_playbook: golang/core.yaml

# Python
- import_playbook: python/core.yaml

# Ruby
- import_playbook: ruby/core.yaml

# rust-lang
- import_playbook: rust-lang/core.yaml

# Node
- import_playbook: nodejs/core.yaml

